apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replica
spec:
  replicas: 1
  selector:
    app: nginxweb
  template:
    metadata:
      labels:
        app: nginxweb
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
       - containerPort: 80
