apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpdhealth
spec:
  replicas: 3
  selector:
    matchLabels:
      service: httpd-health
  template:
    metadata:
      labels:
        service: httpd-health
    spec:
      containers:
      - name: webserver
        image: httpd
        ports:
        - name: nodejs-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
